{% set version = '2.1.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-princurve
  version: {{ version|replace("-", "_") }}

source:
  fn: princurve_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/princurve_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/princurve/princurve_{{ version }}.tar.gz
  sha256: b7dda2e32de62216cd5348166cfff3088eecada808a6a427025d626387d1cf8a

build:
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: devtools, testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpp

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp

test:
  commands:
    - $R -e "library('princurve')"           # [not win]
    - "\"%R%\" -e \"library('princurve')\""  # [win]

about:
  home: https://github.com/dynverse/princurve
  license: GPL-2
  summary: Fitting a principal curve to a data matrix in arbitrary dimensions.
  license_family: GPL2

extra:
   recipe-maintainers:
    - dpryan79
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
