{% set version = "2.0.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-princurve
  version: {{ version|replace("-", "_") }}

source:
  fn: princurve_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/princurve_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/princurve/princurve_{{ version }}.tar.gz

  sha256: 8249b91a292c6e59f49e82bcccfad5edc1d2af63678b86616b6276c8bc2581f9

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('princurve')"  # [not win]
    - "\"%R%\" -e \"library('princurve')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=princurve
  license: GPL-2
  summary: fits a principal curve to a data matrix in arbitrary dimensions
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}\/lib\/R\/share\/licenses\/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
