{% set version = '1.1-12' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-princurve
  version: {{ version|replace("-", "_") }}

source:
  fn: princurve_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/princurve_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/princurve/princurve_{{ version }}.tar.gz

  sha256: fc34fd655984d6fe7100bf083c0889181508398de8246b95b1663fe82ecfd7a5

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('princurve')"  # [not win]
    - "\"%R%\" -e \"library('princurve')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=princurve
  license: GPL-2
  summary: fits a principal curve to a data matrix in arbitrary dimensions
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}\/lib\/R\/share\/licenses\/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
