travis:
  secure:
    BINSTAR_TOKEN: PCXcvdSPRqEIhnQvn/FFNDvNTD6zR/Vsny8lLfh9WG+mtPj67/YrykHCyG0Z1CruYVe8im0Ah77NAt0RuisjXa0PaLB7zqdwCkn+ilo0xtkjto5W2OF3hiXa4eqFjPEc8YPUqbe4AzD3Cy8gK82HSVlW18h4RLIU1Y8qvdOU0kbA74S/yUd/uDzx35f+jA86nhMQPevaScrPTOKRWmqIkILQA01DMp/TMLjxcEw+BHPx9rlaAMsLYSndyN493H/rS3y0zg+T8fJE7zGiirQsoNfrPPooET3VA8nWHe/snv5MuWRCOFUItQHFxaU/X81JnZqMMZd+b1o5wMEDkLE7LAkiKoiByXnym3twtpfWddmbNcMOXwlFBbD69l4lmr03MaI5anooAfDnmaDPCu/qWnsDtFLgwpWdgDr7Tk5kBmvprYzk8txyYclEemmXS+4r9AKk/UQOO7I8DWXRJM6irQqmm5PiYypC8vo8LPHgDGQCX+F9cnPiKRy9wS3CMK5CQnjzVvlOWckOm3YAhIzIk5Lz9FWwjHKDd/Jvgk+6cqkHPzgOF1GedTe51OV00rxeKBADzuB+2PDP+tgGLLgRZDU9WjJz7LlEf/GDl5enIJC3M1kuxI2xvr6Mbu2Yp4BklUOQalYDqynBDjhy92X8DANcSJCFUmYGRojBvp15iiw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
