travis:
  secure:
    BINSTAR_TOKEN: Riu9/7bP4EqXyf5WPROTixyBXemJnEn3GwMV85tRq5zhiWB7oekbKEGorNn61xDI3cChM/hNGI/2xfXL7PbL/WLaid8DmhEpvO39z4dJQV6QTMILc0jP7GpwFI0V+rZey3yeXBm1KhDDV5LhIXsz6HpS8JTlwabaUNQeY/SYIHO6Z2QsB7xNiihlPh7M+rzwX3u/p2mg24UD3jZDvqd+Arz02voTzyWBUpf52fkpl620KLCj7xp29ebxCaLsMYyvPn9cGcZdkoJCKoPivZaH8WjBkvEGYCX1C/QXbCzYigZ1EO6eXFGWKwyknupBeK9bqSIKYB02XLG1w+M1/Sj/r0PWkMhwCUxdeaNV0ZlsaaehSTBSY1iXS4dyJR2U1eAGG01G4VuFC9ORUO491HdrKvagMMJsJCFN/Ztm5HwxrcO72dbNsrnWDPeRQIMx9KCFF0iDeUE7tg2Fr4WUYJrH6HVf/W21Ckp3U9qVTRYa7BbfO3MsGzQxT15hERbd+q2h9SEZ4hCXLJbgXCJXu6rLYZZ09bTJPy26fXz7z0TdZKsofxDVt336zch6bK94xl7tvPpMSaAORog0W4eRDymKPX7s0iDwFTcTz5eSWAekwM2bhSlMyRECf1Kgax6TjG7p/MVByC7Nz3vADjezT3YUKiv2PfExbYwUMZR0/K9f90c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
