travis:
  secure:
    BINSTAR_TOKEN: r8giStWoWmqNsDtTptReQAeHVFEmdjNY9fLY8jAs/xN3trp579DKNtW0yq4X4HoOf8LReFPhiYODeARwkX2V0E6Z6IOBWzPaS2AVEGfYOtxqInjD7yvl0Ks0gJpxyB1t7sJlfh/yvWFqgbv8WSLmHzj/tHCyglfzKYwWpZ5diQg3z46ImJIKjcRBi1kiIhL0rPf+q4HaeIhm/b/EY27gFdH8D2Uk/YZbkFYKDaXIjaFkaGcmm4cKoGRy0JY91ezeV5Jf7hNjf4t0gxxp9XnhqPCBBL6amS45sUnZK7H1vJ2t6zD5Ok+gwne5/Wg20MYm57oHKYxdwg+vUHDjiH8fejB4bWoM50xKEoqi6y47eWKv3umhOgsrihpOqlGXB9+SZiXSUnijTAJ+BS7s8DLRPZTgqPItKKS2+UV0j5ZEKnksh6Ld6YIJLr77YNszvhCk1bwizyLUi1H3WWE4BJSUE9CCIfpbiNXNslnMF48lzKYPBH4mIr7ZiRzgiR9ns9o7SsmyU8wQtiUY4JCDq1NW5NZRfhpKGqcxcmlNVZT+j1tIBPMSSQIzhrBHqWvklNnMj0nkY3cN7a73QP5b0ttayGWz3a6pdda0NQ42336asPr6u13V0A+WYQR9ig02iHXJNH8dv0Ouz+5DrbUenNgf1sCGWAPw5xvbxhgbDzNUKFk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
