appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: VupC6merjIcRRJUEXX+mNNG/YdQQyBxFmKCRAO5XKdMDNYbIHiiY3MM6xC2+qfpijcjUIU/+QEc3TNpCBCVxOPpbxvSfp1vWK6Ob5LMlTbSlDePe3uOfsIQAOHK4iDh5gmDkGENiJGtuZdDHI9fQ2k4nsQBuPYGOnMH28AMaZQJLjUvzDV+IyEey6bSUipr1sotTrfbxm077g2dYlgXoYwRkxs9Q+c6nc/Mw0s3IN51G55EO3/tSwoLFZi87TLfkJ3kx69q4URKhxam9nnh2o4fPmdop9Ln06T1G3qnxyGh8t+Lh9/85R0NoFtNb1ZpVwl9oKRo35pquF7h6MkFmsCLh/RmTJIU7iUsvFi1RfDjUb9GlwNFMry0qtLsXWSyS3N+q3aazxgkIN9hkqtT1B257W6fBoItqWAn0WT9PCGvEOHKDT/0ZvQoM7NbqEoT+rUOXD1MBrVLe4dX7u8zZ8a4PoulFEcOzBYD/D1jcKsTFU+KPEdEC/70vOBmnNwpx9l3Z2TADJ5k5AM+g2YLYZkD0SvYe+/usNGh0Q80/h/cPlkUQRGkweoRwNxNxBKi1KRPQS00fOi87RJpZD0X7gekJiKd/sVHaTIrZWnkKAMs+Z4Q2u/6VQ+CpJD6kNvj+GWFQ8l586eBFs9jePa1WH8+zXhyRy67ouZPJmSnDAnM=
conda_forge_output_validation: true
